name: ml-trading
channels:
  - defaults
dependencies:
  - python=3.12.9
  - numpy=2.2.5
  - pandas=2.3.1
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - statsmodels=0.14.5
  - matplotlib=3.10.0
  - plotly
  - shap=0.47.2
  - numba=0.61.2
  - llvmlite=0.44.0
  - bottleneck=1.4.2
  - py-xgboost=2.0.3
  - xgboost=2.0.3
  - joblib=1.5.1
  - tqdm=4.67.1
  - requests
  - cloudpickle=3.1.1
  - pyparsing=3.2.0
  - patsy=1.0.1
  - openpyxl=3.1.5
  - packaging
  - pip
  - pip:
      - beautifulsoup4==4.13.4
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - clarabel==0.11.1
      - curl-cffi==0.13.0
      - cvxpy==1.7.1
      - ecos==2.0.14
      - frozendict==2.4.6
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - multitasking==0.0.12
      - osqp==1.0.4
      - peewee==3.18.2
      - platformdirs==4.3.8
      - plotly==5.24.1
      - protobuf==6.32.0
      - pycparser==2.22
      - pyportfolioopt==1.5.6
      - requests==2.32.5
      - scs==3.2.8
      - soupsieve==2.7
      - tenacity==9.1.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - yfinance==0.2.65
