"""Hand-labeled VCP benchmark — 200 charts judged blind against frozen price data.

Protocol (2026-07-03): each chart was judged by eye from its raw weekly (30w) and daily
(45d) OHLCV tables — swing structure, pullback depths, volume behavior, distance from the
52-week high — with NO detector output visible at judgment time. Verdicts were recorded
before unblinding. Data vintage is frozen in ``tests/fixtures/vcp_bench/*.parquet``
(histories truncated at LABEL_DATE), so these labels stay valid regardless of what the
live price cache does.

Label semantics:
  YES = a live/actionable VCP-style setup as of LABEL_DATE — a contracting base that is
        forming, at, or within the buy zone of its pivot. The detector must NEVER put a
        YES chart in tier C (the never-miss contract).
  NO  = everything else, including textbook bases that had already broken out and run
        well past the buy zone (pattern spent = not actionable).

Batches 1-5 (the first 40) were labeled across two sessions on 2026-07-03; the remaining
160 follow the identical protocol against the frozen fixtures.
"""

LABEL_DATE = "2026-07-03"

# Windows-reserved device names can't be used as git-tracked filenames; those
# fixtures carry a trailing underscore on disk (e.g. CON -> CON_.parquet).
_WIN_RESERVED = {"CON", "PRN", "AUX", "NUL"} | {f"COM{i}" for i in range(1, 10)} | {f"LPT{i}" for i in range(1, 10)}


def fixture_filename(ticker: str) -> str:
    """Return the on-disk parquet filename for a benchmark ticker."""
    stem = f"{ticker}_" if ticker.upper() in _WIN_RESERVED else ticker
    return f"{stem}.parquet"

# ticker -> {"label": "YES"|"NO", "reason": one-line judgment}
LABELS = {
    # ---- original 40 (blind sessions 1 & 2, 2026-07-03) ---------------------
    "CALY": {"label": "NO", "reason": "Single deep May leg (-21%), peaks rising not flat; broke out mid-June, now post-breakout"},
    "CDNA": {"label": "NO", "reason": "Textbook completed VCP (22->12->9%) but broke out Jun 18 and ran ~21% past pivot - spent"},
    "CERS": {"label": "NO", "reason": "$3 biotech chopping 2.3-3.2; swings -26/-23% with no tightening, volume rising"},
    "CHEF": {"label": "NO", "reason": "Completed VCP (10->4%), broke out Jun 11, +15% past pivot; new flag only ~2 weeks old (borderline)"},
    "CNC":  {"label": "YES", "reason": "June flag under flat 65.7-66.5 top: -10.0% then -3.1%, higher lows, fresh Jul 1 breakout in buy zone (marginal)"},
    "CPA":  {"label": "NO", "reason": "Rising recovery (peaks 134->160, never flat); single -11% June dip already resolved; post-breakout"},
    "EQ":   {"label": "NO", "reason": "+900%-off-low runner chopping +/-20%; violently rejected its high two days before label date"},
    "KRYS": {"label": "NO", "reason": "Depths tighten (10.5->9.7->5.3->5.3) but peaks rise 20% - stair-step advance, not a base (borderline)"},
    "MEC":  {"label": "NO", "reason": "Parabolic 2x runner rolling over; legs -25/-9/-7 then EXPANDING -15% on rising volume"},
    "MKSI": {"label": "NO", "reason": "Vertical run to 447 smashed -18% in two days on heavy volume; no base"},
    "PLPC": {"label": "NO", "reason": "Was tightening (12->8->5%) but last leg blew out -13.5% in 2 days - pattern failed"},
    "PRG":  {"label": "NO", "reason": "Completed VCP (11.4->11.9->5.6%), 4-5x vol breakout Jun 26, now +11% extended - spent"},
    "SLAB": {"label": "NO", "reason": "Deal stock: Feb gap then five months pinned 204-220 with sub-2% weekly ranges; no swings"},
    "TSBK": {"label": "YES", "reason": "15.7->9.0->5.1% taper, rising lows, 5-7x volume pop Jun 23, +2.5% above pivot (illiquid microcap)"},
    "TWO":  {"label": "NO", "reason": "Mortgage REIT dead-flat at ~12 for 8 weeks, 10% below Jan high with a -38% crash between"},
    "UTI":  {"label": "NO", "reason": "-21% June collapse then 12-day V straight back to highs; swings expanding, no base"},
    "VCEL": {"label": "NO", "reason": "Completed VCP (22->12->4.7%), broke out Jun 26, now +15% above base top - spent"},
    "VNCE": {"label": "NO", "reason": "Post-spike rectangle: two -20% drops from 8.20, zero tightening, price at range low"},
    "VRA":  {"label": "YES", "reason": "Forming VCP 28.7->15.2->8.1% (depths halving), rising lows, 90x accumulation day, coiling under pivot"},
    "WLFC": {"label": "NO", "reason": "-29.5% crash then V-sprint back; only a ~1.5-week shelf at 219-230, no contraction sequence"},
    "ALRS": {"label": "NO", "reason": "Smooth bank-grinder rising channel; dips -7.7/-3.5/-2.7% but no distinct base to break out of"},
    "ASND": {"label": "NO", "reason": "Breakaway gap 5 days before label date (+13% on 5-8x volume), above every prior peak; no base yet"},
    "ATRO": {"label": "NO", "reason": "Parabolic 64->88.7 then violent 3-day -20% collapse on rising volume"},
    "AXGN": {"label": "NO", "reason": "Flat 38-46 top but wild right side: two -10% single-day shakeouts in the final week"},
    "BDSX": {"label": "NO", "reason": "Ultra-thin microcap +63% in two weeks, now cracking -12%; post-runaway, no base"},
    "BFC":  {"label": "YES", "reason": "4.5-month flat base: -15 -> -10 -> -5%, rising lows, broke the 150 pivot Jul 1, in buy zone"},
    "CON":  {"label": "NO", "reason": "Six-week continuous advance closing at highs daily; dips contract but peaks rise 20% - nothing coiled"},
    "CSCO": {"label": "NO", "reason": "4-week descending correction: lower highs/lows, 51M-share distribution break, new low at label date"},
    "ELSE": {"label": "NO", "reason": "Tender-offer zombie: +42% April gap then ten weeks pinned at 7.6x with penny ranges"},
    "ETON": {"label": "YES", "reason": "Cup -25% + tight 2-week -4.5% shelf, breakout through 35.66 pivot this week, buy-zone edge (lean)"},
    "FBNC": {"label": "YES", "reason": "16.9 -> 8.6 -> 4.6 -> 4.4% taper under Feb high, 3-4x vol breakout, +2.6% above pivot"},
    "IFF":  {"label": "YES", "reason": "15.0 -> 11.0 -> 7.4%, rising lows, breaking through 83.5 double-top pivot at label date"},
    "INTG": {"label": "NO", "reason": "-27% decline, +58% vertical spike in 7 days, then +/-8-16% intraday chop; volatility maximal"},
    "MNST": {"label": "NO", "reason": "Continuous 86->99 post-earnings advance with 3% noise dips; never built a base"},
    "PK":   {"label": "YES", "reason": "3-week flat shelf 13.8-14.7 after +21% markup: legs -5.9/-5.0%, rising lows, clear 14.69 pivot (weak/flat-base variant)"},
    "PRLD": {"label": "NO", "reason": "-39% decline, +51% V-recovery, brief new high then -14% two-day rejection"},
    "PTGX": {"label": "NO", "reason": "Clean 3-month flat base but broke out Jun 9 and ran +22% past the pivot - spent"},
    "RLGT": {"label": "YES", "reason": "21.6 -> 11.9 -> 8.1 -> 8.1%, rising lows, 5x volume Jun 26, +0.4% above 9.45 pivot"},
    "SMBC": {"label": "YES", "reason": "Pristine 9.4 -> 6.4 -> 5.5 -> 4.2% taper, rising lows, 3-5x vol breakout, +8% slightly extended"},
    "TRNS": {"label": "YES", "reason": "4-week base under very flat 94-95 top: -10.0 -> -7.7 -> -6.3%, rising lows, pre-breakout (lean; wide-loose context)"},
    # ---- batches 6+ (the 160 new charts) appended below as labeled ----------
    "ACRS": {"label": "NO", "reason": "Ragged 8-week 4.1-5.15 range: legs -17.9 -> -14.7% barely tighter, lows fell mid-base; broke out on volume but already +8% past the range top"},
    "AGX":  {"label": "NO", "reason": "Wild runner: -26% June crash, V-recovery to 805, fresh 2-day -12% drop at label date; swings expanding, never a base"},
    "AIN":  {"label": "NO", "reason": "Stair-step advance, peaks rising ~20% (63.8->76.6); dips contract but no flat-top consolidation"},
    "ALGM": {"label": "NO", "reason": "Blow-off spike to 71.77 then -26% two-day collapse to 52.88; expansion, no base"},
    "ALTO": {"label": "NO", "reason": "Penny runner, legs -28 -> -19% still huge; Jul 1 marginal-new-high poke faded -9% next day"},
    "ALX":  {"label": "YES", "reason": "Thin REIT but real June flag: -7.1 -> -2.6% under flat 267-271 top, higher lows, fresh breakout +1.5% above pivot (weak)"},
    "AMAL": {"label": "YES", "reason": "Bank base: taper 15.3 -> 7.7 -> ~4-5%, rising lows, flat 42-43 top, 5x vol breakout Jun 26, ~+2% above June pivot"},
    "AMTB": {"label": "YES", "reason": "Taper 14.7 -> 12.8 -> 5.4%, rising lows 19.9->21.2->22.9, flat top, 4x vol breakout Jun 24, within buy zone"},
    "AMWL": {"label": "NO", "reason": "Consolidating under 9.96 but legs -17.8 -> -13.4% still loose for a $9 stock; constructive watch, not coiled"},
    "APGE": {"label": "NO", "reason": "Acquisition: gapped to ~133 on 62M shares Jun 22, sub-1% range for 9 days since; deal-pinned dead tape"},
    "ATLC": {"label": "NO", "reason": "Stair-step run topped 112.61 Jun 26, then 4 days into a -15% slide (last day -7%); expansion, no base"},
    "AVBC": {"label": "YES", "reason": "Recent-IPO bank: taper 13.4 -> 6.6 -> 5.6%, rising lows, flat 20.6-21.4 top, 25x accumulation day, breaking out at pivot"},
    "BATRA": {"label": "YES", "reason": "7-week flat base under 56: legs 6.0 -> 5.7 -> 3.0%, quiet volume, 2-3x vol breakout Jun 24, +2.9% above pivot"},
    "BB":   {"label": "NO", "reason": "Meme parabola +43% in 5 days to 13.59 then -15% single-day reversal at label date; no base"},
    "BEAM": {"label": "NO", "reason": "2-week 11%-wide chop box at highs (16 -> 11 -> 11%) on a chronically volatile biotech; never tightens, no dry-up"},
    "BEN":  {"label": "NO", "reason": "Rising channel with uniform ~6% dips (5.9/6.7/6.2) - shallow but no contraction sequence"},
    "BFH":  {"label": "NO", "reason": "May shelf broke out Jun 9 and ran to 109.9 (~+15% past pivot); now 2-day -8% drop - spent and pulling back"},
    "BJRI": {"label": "NO", "reason": "Ascending flag-sequence, peaks 53.5->62.1 (+16%); tight flags but no consolidation base; 2 days off high"},
    "BLBD": {"label": "YES", "reason": "Post-spike base under May 81.51 pole: taper 15.2 -> 5.7 -> 2.8%, rising lows, 3x vol thrust Jun 25-26, +1.4% above 75 shelf after retest"},
    "BNL":  {"label": "NO", "reason": "Low-vol REIT grinding at highs: uniform ~5.5% dips, no contraction, no distinct pivot"},
    "BOH":  {"label": "YES", "reason": "10-week flat base under 82 (Jun 1 spike = one-day shakeout): legs 10 -> 10 -> 6.1%, fresh breakout +1.0% above pivot; weak volume (lean)"},
    "BOTJ": {"label": "NO", "reason": "Ultra-thin 26k sh/day with zero-volume days; 52wH is a single thin print; prints not patterns"},
    "BWEN": {"label": "NO", "reason": "Post-moonshot penny (+117% day in May): +/-20-30% weekly chop, -24% leg into late June"},
    "BYFC": {"label": "NO", "reason": "5k sh/day with repeated no-trade days; untradeable, unjudgeable tape"},
    "BZH":  {"label": "NO", "reason": "Post-gap recovery tightened 18 -> 6.7% but current 3-day dip (-8.5%) is wider than the prior leg; ascending peaks, expanding at label date"},
    "CAKE": {"label": "NO", "reason": "May base broke out Jun 8 and ran +20% past pivot; remaining flag is tight but ascending/continuous - nothing coiled"},
    "CBNA": {"label": "NO", "reason": "15k sh/day with near-zero-volume days (prints not patterns); shelf breakout already +8.6% past top in 3 days"},
    "CCCC": {"label": "NO", "reason": "Penny biotech +/-15-25% chop; Jun 30 spike to 5.17 faded -17% in two days"},
    "CCNE": {"label": "YES", "reason": "Bank VCP: taper 14.3 -> 9.1 -> 8.9 -> 5.1%, rising lows, 4x vol day Jun 26, +1.4% above June flag pivot"},
    "CCSI": {"label": "YES", "reason": "5-week post-gap base 29 -> 10.5 -> 9.2% with flat lows, breakout through 37.3 pivot Jul 1, +1.7% above after hot thrust faded (lean)"},
    "CEVA": {"label": "NO", "reason": "Triple rejection at ~51 with -19%/-17% legs; expanding volatility, breakdown in progress, 22% off high"},
    "CGEM": {"label": "NO", "reason": "-30% June flush then V-spike to marginal new high fading -11.5%; no contraction"},
    "CHMG": {"label": "YES", "reason": "Bank base: legs 8.2 -> 4.9 -> 5.6%, rising lows 64.7->66.6->69.4, fresh breakout Jun 23-26 on 2-4x volume, +1.4% above pivot"},
    "CLDX": {"label": "NO", "reason": "Legs 18 -> 12% but second low undercut the first; breakout already +7.2% past pivot; loose and slightly late"},
    "CLMT": {"label": "NO", "reason": "Three ~18% oscillations (18.2/16.0/18.3) across a 30-38.75 range; zero contraction"},
    "CM":   {"label": "YES", "reason": "Large-cap coil: legs 9.6 -> 3.7 -> 2.7%, rising lows, flat 116 top, at pivot (Jul 1 poke faded, structure intact)"},
    "CNI":  {"label": "YES", "reason": "Two-month coil under ~122: rising lows 108.3->112.5->119.0, final leg -1.6%, knocking on the 121.8 pivot"},
    "CNS":  {"label": "YES", "reason": "Taper 7.6 -> 5.5 -> 4.9%, rising lows 68.0->74.4->74.7, flat 78.5-79.3 top, at pivot"},
    "CNXN": {"label": "NO", "reason": "Uniform ~9% dips (9.0/8.7) under rising peaks; Jul 1 marginal-high poke faded -3.8% in 2 days"},
    "CPRX": {"label": "NO", "reason": "Deal-pinned: eight weeks of 0.1-0.7% weekly ranges at ~31.3 (acquisition arb); dead tape"},
    "CRI":  {"label": "NO", "reason": "Double-top test at 43.5-44.3 then 4 straight down days (-9.1%, no stabilization); prior legs -26/-18%"},
    "CTRN": {"label": "NO", "reason": "Parabolic to 66.38 then -19% single-day collapse Jun 25 on 5x volume; +/-16-25% weekly ranges"},
    "CURB": {"label": "NO", "reason": "REIT grinder; last leg (-6.7% with 4x-volume down day) wider than prior (-3.9%); expanding not coiling"},
    "CVV":  {"label": "NO", "reason": "Microcap +/-20-45% weekly swings (-44% May flush, -24% June leg); pure noise"},
    "CYRX": {"label": "NO", "reason": "Base under 16.7 tightened 14.6 -> 5.6% but third pivot test just rejected -7% (wider than prior leg) (lean)"},
    "CZWI": {"label": "YES", "reason": "6-week quiet bank shelf: legs 6.1 -> 4.9 -> 4.6%, 5-10x volume breakout through 22.5, +5.2% at buy-zone edge (lean)"},
    "DAL":  {"label": "YES", "reason": "June base 8.9 -> 6.3%, breakout Jun 24-25, +6.1% above 87.4 pivot in tight 4% drift - marginally extended (lean)"},
    "DAVE": {"label": "NO", "reason": "Vertical +41% 3-week melt-up with +/-10% daily ranges; no base"},
    "DE":   {"label": "YES", "reason": "4-month taper under Feb 670 pivot: legs 18.2 -> 13.3 -> 7.9%, rising lows 514->555, pre-breakout -7.3% below pivot"},
    "DELL": {"label": "NO", "reason": "Post-spike month of +/-12-24% swings below the 469 blow-off (24/10/13/14% legs); no contraction"},
    "DGICB": {"label": "NO", "reason": "3.7k sh/day B-share, mostly zero-volume identical prints; untradeable"},
    "DHX":  {"label": "NO", "reason": "7-week +/-15% box after a spike (legs 15.4/14.8/15.0/11.8); no tightening at $3.70"},
    "DNLI": {"label": "NO", "reason": "Two wide legs (13.8 -> 10.7%), breakout already +8.6% past Feb pivot; loose biotech base, past the zone (lean)"},
    "DSGN": {"label": "NO", "reason": "-41% May crash then +58% 4-week V-sprint into overhead supply; no consolidation"},
    "DVA":  {"label": "NO", "reason": "May shelf broke out Jun 11 and ran +16.6% past the 202.7 pivot; extended vertical drift"},
    "ECPG": {"label": "YES", "reason": "6-week base tapering 9.1 -> 7.0 -> 6.4%, breakout through 86 shelf, +5.3% above after Jul 2 fade - buy-zone edge (lean)"},
    "EIX":  {"label": "YES", "reason": "Utility coil: taper 13.0 -> 9.5 -> 4.5%, rising lows 65.0->68.9->70.5, sitting -0.4% below the 76.22 pivot"},
    "ELVN": {"label": "NO", "reason": "Legs widened 20.5 -> 22.3% into June, then +30% news gap and 3-week ascent; no contraction structure"},
    "EPC":  {"label": "NO", "reason": "-30% May crash then +77% V-sprint to new highs without a pause; nothing coiled"},
    "ESOA": {"label": "NO", "reason": "-26% flush, recovery rejected under the 19.9 pivot with live -9% fade (wider than prior leg)"},
    "EVC":  {"label": "NO", "reason": "June box tightened (26->16->11%) but broke out Jun 23 and ran +30-38% past pivot in 7 days; extended"},
    "EXEL": {"label": "YES", "reason": "7-week base, final leg 5.8%, rising lows 48.1->50.8, 2.5x vol breakout Jun 26, +3.6% above pivot"},
    "FATE": {"label": "NO", "reason": "Penny biotech +/-15-38% ranges then +50% 3-day spike into label date; no base"},
    "FBIOP": {"label": "YES", "reason": "Thin preferred: post-run shelf under 21.43, weekly ranges collapsing 7.9->6.3->2.7->2.4%, coiled -4.8% under pivot"},
    "FBP":  {"label": "YES", "reason": "Taper 15.2 -> 6.2 -> 4.1%, staged bank breakout Jun 12, +1.8% above the June flag pivot"},
    "FISI": {"label": "YES", "reason": "Bank taper 17 -> 6.8 -> 5.7 -> 5.6%, rising lows 28.9->36.4, staged breakout on 2x volume, near pivot"},
    "FMAO": {"label": "YES", "reason": "Textbook: 20.6 -> 11.1 -> 6.5 -> 3.3%, flat top, 3x vol breakout Jun 24-26, +3.7% above the 29.57 pivot"},
    "FMX":  {"label": "YES", "reason": "-13% then uniform ~6% legs under flat 130-132 top, rising lows, at pivot; taper imperfect but coiled (lean)"},
    "FNRN": {"label": "NO", "reason": "Last leg -9.9% on record volume (2x prior leg width); distribution week at label date on formerly near-dead tape"},
    "FRD":  {"label": "NO", "reason": "+49% June moonshot then +/-14-16% chop with widening legs; violent tape"},
    "FTNT": {"label": "YES", "reason": "Post-gap 4-week flag under 147-153: legs 11.3 -> 6.5 -> 6.1%, breakout Jul 1-2, +2.3% above pivot (lean)"},
    "GCBC": {"label": "NO", "reason": "6-week +32% ascent with WIDENING weekly ranges (9.5 -> 13.4%); loud climb, no coil (thin bank)"},
    "GEO":  {"label": "NO", "reason": "May shelf broke out Jun 8 and ran +29% past the 23.8 pivot; June stair-climb with uniform 5-7% dips"},
    "GEV":  {"label": "NO", "reason": "Two-month +/-10-16% oscillating mega-range below 1181; legs never tighten (12.8/15.8/10.4/11.1)"},
    "GLUE": {"label": "NO", "reason": "45%-deep 5-month cup with a 2-week +40% vertical right side; no handle, wide legs throughout"},
    "GOLF": {"label": "NO", "reason": "+40% 3-week vertical June sprint; one quiet 4-day week isn't a base"},
    "GRBK": {"label": "YES", "reason": "4-month cup: taper 24.7 -> 14.9 -> 3.0%, rising lows, breakout attempt to 83.18, retesting from just below the 81 pivot"},
    "GRDN": {"label": "NO", "reason": "Chronic 7-15% weekly ranges, legs 22 -> 13% still wide, high-volume shakeout week 10 days before label date"},
    "GTY":  {"label": "YES", "reason": "10-week flat base under 34.25: legs 7.0 -> 4.6 -> 4.7%, breaking out at the pivot on 2x volume at label date"},
    "HFBL": {"label": "NO", "reason": "2k sh/day; 52wH is a one-day thin print; untradeable"},
    "HFWA": {"label": "YES", "reason": "Bank taper 15.7 -> 9.4 -> 6.2%, rising lows 24.2->25.8->27.3, 2x vol breakout Jun 26, +3.4% above pivot"},
    "HLIO": {"label": "NO", "reason": "Stair-climb to 95.05 then a -13% one-week break into the label date; expanding"},
    "HLIT": {"label": "NO", "reason": "Post-spike chop 13-17.7: legs 25 -> 14 -> 6 then re-expanding to 16% in the final week"},
    "IMUX": {"label": "YES", "reason": "Taper 26.8 -> 10.9 -> 8.1% under flat 15.4-15.8 triple-top, rising lows 11.6->13.5->14.5, coiling below pivot (weak; volatile biotech)"},
    "IPSC": {"label": "NO", "reason": "Penny biotech, +/-9-22% weekly ranges, 20% below high in a chop-box"},
    "IRDM": {"label": "NO", "reason": "June correction with descending highs, then +23% news gap 2 days before label date, already fading; no base"},
    "JAKK": {"label": "YES", "reason": "4-month taper 18.1 -> 14.1 -> 8.6%, rising lows, flat 23-24 top, drying volume, coiled -3.1% under pivot"},
    "KB":   {"label": "NO", "reason": "97-120 mega-range: legs 19.0 -> 12.5 -> 16.3 re-widened; Jun 26 flush retested range low then V-bounce"},
    "KLIC": {"label": "NO", "reason": "Vertical run to 135.8 then -13.6% in the two days at label date; blow-off break"},
    "KN":   {"label": "NO", "reason": "Climb to 42.93 then two -11/-13% down-legs in the final two weeks, closing at the low"},
    "KORE": {"label": "NO", "reason": "Deal-pinned: four months of sub-1% weekly ranges at ~9.1 after the Feb gap; dead tape"},
    "KPTI": {"label": "NO", "reason": "Penny biotech oscillating +/-11-33% for months; no contraction"},
    "LINE": {"label": "NO", "reason": "Flat 44.5-44.8 triple top but legs widened (9.5 -> 11.8% with lower low) then V-back to pivot; sloppy (lean)"},
    "LLYVK": {"label": "YES", "reason": "4-month base under 102-104: legs ~14 -> 11 -> 7 -> 7%, rising lows, breakout Jul 1-2 to +3.6% above pivot (lean)"},
    "MAC":  {"label": "NO", "reason": "Clean 7-week shelf broke out Jun 8 and ran +12-13% past the pivot; new flag only ~1.5 weeks old (lean)"},
    "MAMA": {"label": "NO", "reason": "+/-9-19% ranges then a +55% 3-week sprint to 21.00 fading -11% at label date"},
    "MAS":  {"label": "YES", "reason": "Taper 26.3 -> 16.9 -> 5.2%, rising lows 57.9->63.0->72.3, breakout through Feb 78.5 pivot, +5.5% buy-zone edge"},
    "MATX": {"label": "YES", "reason": "3-week flag 6.6 -> 2.7% under flat 202-203 top, breaking out at label date, at pivot"},
    "MCFT": {"label": "NO", "reason": "Post-spike base attempt rejected: approach to 26.25 faded -9% in the final two days; legs still 12-13%"},
    "MD":   {"label": "YES", "reason": "Taper 14 -> 6 -> 6%, rising lows, breakout through 24.7, +8.3% slightly extended (lean, SMBC-class)"},
    "MGM":  {"label": "NO", "reason": "Post-surge 46-51.6 box: legs 10.5 -> 6.4 -> 7.5 re-widened, price at box low at label date (lean)"},
    "MPC":  {"label": "NO", "reason": "June leg (-12.5%) wider than May's (-8.6%), then 2-week V straight back to pivot; no contraction"},
    "MRVI": {"label": "NO", "reason": "+20% surge week into a 6.55 spike fading -8%; $6 stock with 9-27% ranges"},
    "MSBI": {"label": "YES", "reason": "Bank taper 7.3 -> 6.0 -> 5.0%, rising lows, 2.3x vol breakout Jun 24, retesting the 30.3 pivot"},
    "MSGS": {"label": "NO", "reason": "Steady staircase with uniform 5-10% dips; no flat-top base; fresh high faded -4% at label date (lean)"},
    "MTH":  {"label": "YES", "reason": "W-base taper 28.5 -> 17.6 -> 6.1%, breakout through Feb 80.6 pivot Jun 24-26, +1.5% above after fade"},
    "NECB": {"label": "YES", "reason": "Bank taper 8.7 -> 7.5 -> 5.9 -> 3.3%, rising lows, 2.5x vol breakout Jun 24, +6-8% slightly extended"},
    "ORKA": {"label": "NO", "reason": "8x biotech: +25% surge into a 97.78 spike then -13% two-day fade; +/-10-32% ranges"},
    "OSS":  {"label": "NO", "reason": "Post-gap +/-16-22% chop with -30/-25/-20% legs; 25% off high"},
    "OUT":  {"label": "YES", "reason": "Textbook taper 10.9 -> 9.8 -> 5.9 -> 3.7% under the 34.63 pivot, right side on 2x volume, -5% below pivot"},
    "PCB":  {"label": "YES", "reason": "Bank taper 12.0 -> 6.1 -> 3.0%, 3x vol breakout Jun 26, +6.3% slightly extended (SMBC-class)"},
    "PDFS": {"label": "NO", "reason": "Spike to 71.69 then a -21% single-day collapse to 56.96 at label date; +/-13-22% ranges"},
    "PEBO": {"label": "YES", "reason": "Bank taper 10.3 -> 6.5 -> 3-4%, breakout Jun 24, +5.1% buy-zone edge"},
    "PFIS": {"label": "YES", "reason": "Bank taper 12.4 -> 11.4 -> 6.3 -> 6.1%, breakout Jun 24-26, +3.4% above pivot"},
    "PKOH": {"label": "NO", "reason": "Thrust to 39.33 rejected -8.8% in 3 days back into the base; legs plateaued 10-11% (lean)"},
    "PLBC": {"label": "YES", "reason": "Bank taper 13.4 -> 6.7 -> 3.9%, breakout to 60.47, +2.8% above pivot (thin; one flash print)"},
    "PMTS": {"label": "NO", "reason": "Chronically 10-21% weekly ranges, legs -24/-15/-13%; 20% below its 52wH"},
    "PNTG": {"label": "YES", "reason": "8-week post-gap base under 37.5 with one mid-base shakeout, breakout Jun 26-Jul 2, +2.6% above pivot (lean)"},
    "PSNL": {"label": "NO", "reason": "Vertical +35% surge week into label date after +/-11-28% chop; nothing coiled"},
    "PSX":  {"label": "NO", "reason": "Double-top rejection at 188-189 with a -12.7% leg (wider than prior -8.0%); mid-range chop"},
    "RAL":  {"label": "NO", "reason": "2-month +60% staircase then a -9.3% four-day fade at label date; last leg widest"},
    "RAMP": {"label": "NO", "reason": "Deal-pinned: six weeks of 0.6-1.5% ranges at ~37.6 on decaying arb volume; dead tape"},
    "RFL":  {"label": "NO", "reason": "Penny moonshot +150% in 4 weeks (+/-23-37% ranges), now -20% off the spike"},
    "RLAY": {"label": "NO", "reason": "6x biotech, +/-10-26% ranges, -24% June leg then 3-week +40% V-march; no coil"},
    "RLYB": {"label": "YES", "reason": "Post-gap coil: ranges 13.7 -> 10.4 -> 4.5 -> 4.3%, flat 16.4-16.5 top, extreme vol dry-up (0.16x), -4% under pivot (lean; thin)"},
    "RNST": {"label": "YES", "reason": "Bank taper 19.0 -> 5.5 -> 5.7 -> 4.7%, rising lows 33.7->40.9, at the 44 pivot"},
    "RUSHB": {"label": "YES", "reason": "Cup: -20% left side, right-side dips 5.2 -> 4.7%, approaching the 78.9 pivot from -4.8% below"},
    "SEZL": {"label": "NO", "reason": "8 straight up-weeks +130% with +/-11-16% ranges, closing at the high; vertical, no base"},
    "SGC":  {"label": "NO", "reason": "-18.7% record-volume flush week one week before label date; legs expanding"},
    "SIF":  {"label": "NO", "reason": "6.5x runner with +/-12-32% weekly ranges; +19% surge week into label date"},
    "SIRI": {"label": "YES", "reason": "Taper 12.1 -> 7.2 -> 4.5%, rising lows 26.5->27.4, breakout through 30.11 pivot at label date, +1.3%"},
    "SLF":  {"label": "NO", "reason": "Smooth rising channel at ATH with uniform ~3% dips; no discrete base or pivot (lean; staircase)"},
    "SLS":  {"label": "NO", "reason": "11x penny; +100% two-week moonshot into label date; +/-17-33% ranges"},
    "SOTK": {"label": "NO", "reason": "$5 microcap; one-day spike to 6.24 faded -17% immediately; choppy tape"},
    "SPG":  {"label": "YES", "reason": "8-week shelf (4.7 -> 3.8 -> 3.1%), breakout, 3-week flag, second breakout Jun 26 on 2.5x vol, +2.5% above pivot"},
    "SRRK": {"label": "NO", "reason": "June leg widened to -17.2% (vs 7-8% prior), then a V-thrust +16% breakout week; no taper"},
    "STBA": {"label": "YES", "reason": "Bank taper 13.3 -> 5.5 -> 4.4 -> 3.3%, rising lows, staged breakout, at the pivot"},
    "SXI":  {"label": "NO", "reason": "5-week +25% run into a 363.89 spike, then -10% single-day reversal at label date"},
    "SYRE": {"label": "NO", "reason": "Spike to 102.06 reversed -20% intra-week on record volume; +/-11-20% ranges; 15% off high"},
    "TFSL": {"label": "YES", "reason": "Thrift taper 12.5 -> 6.4 -> 4-5%, rising lows 13.0->16.1, breakout +4.9% in buy zone"},
    "TIGO": {"label": "YES", "reason": "Taper 15.7 -> 11.0 -> 6.5%, flat 94.2-94.7 top, breaking out at label date +0.7%"},
    "TILE": {"label": "YES", "reason": "Cup recovery: taper 10.9 -> 7.0 -> 5.7%, breakout through the Feb 35.03 pivot Jun 24, +1.8%"},
    "TRIN": {"label": "YES", "reason": "7-week ultra-tight BDC shelf (legs 3.6 -> 2.4 -> 2.0%), breakout through 17.2 at label date, +3.6%"},
    "TRN":  {"label": "NO", "reason": "Recovery rejected under the 37.4 pivot; final-week leg re-widened to -9.3% (vs -4.2% prior), closing weak"},
    "TRVI": {"label": "NO", "reason": "+30% June thrust; now +12-14% past the old pivot in a 2-week-young flag (lean; MAC/CHEF-class)"},
    "TVTX": {"label": "YES", "reason": "Staircase taper 15.0 -> 12.8 -> 7.0%, breakout to 60.10, retesting +1.7% above the 55.99 pivot (lean; sloppy)"},
    "TWST": {"label": "NO", "reason": "+49% four-week vertical with +/-13-22% ranges into label date; no base"},
    "UTMD": {"label": "YES", "reason": "Taper 13.0 -> 6.9%, breakout through 71.5, +1.8% in buy zone (lean; thin ~$1M/day, one flash print)"},
    "UVSP": {"label": "YES", "reason": "Bank taper 13.2 -> ~6% uniform, rising lows 31.2->40.4, 2x vol breakout, +2.0% above pivot"},
    "VCYT": {"label": "NO", "reason": "Cup right side = 7-week +50% run with +/-11-15% legs, fading -6.3% off fresh high; no contraction"},
    "VOYA": {"label": "YES", "reason": "Shelf taper 6.5 -> 4.5%, breakout, 3-week 4.7% flag, fresh second breakout +1.6% at label date (SPG-class)"},
    "VSAT": {"label": "NO", "reason": "-35% June collapse then +42% news-gap moonshot 2 days before label date, already fading -11%"},
    "VTRS": {"label": "NO", "reason": "8-week base under 17.40 but the June leg widened to -10.2% (deepest of the base) before a V-recovery; no taper (lean)"},
    "WABC": {"label": "YES", "reason": "Bank taper 10.3 -> 4.1 -> 3.4 -> 3.2%, rising lows, ultra-quiet grind breaking out at the pivot at label date"},
    "WERN": {"label": "YES", "reason": "3-week coil under 45.27: legs 12.3 -> 6.8 -> 5.4%, rising lows 39.7->42.1, -4.6% below pivot"},
    "WEYS": {"label": "NO", "reason": "Thin staircase: dips 10.6 -> 5.8 -> 8.8% (re-widened), closing at ATH with no discrete coil (lean)"},
    "WSBK": {"label": "NO", "reason": "6k sh/day (~$80k/day) thrift; months of 1-2% print drift; untradeable"},
    "WSC":  {"label": "NO", "reason": "Thrust to 29.77 failed; -10.4% three-day break into the label date, closing weak"},
    "WTBA": {"label": "YES", "reason": "Bank taper 15.2 -> 10.5 -> 4%, 3x vol breakout through the Feb 26.07 pivot, +3.9%"},
    "ZD":   {"label": "YES", "reason": "Taper 19.0 -> 9.6%, rising lows, breakout through the 49 top, +7.1% slightly extended (lean; SMBC-class)"},
}
